image: fedora

before_script:
  - dnf update -y
  - dnf install findutils gcc gcc-c++ make cmake SDL2-devel SDL2-static -y
  - dnf install glm-devel stbi-devel assimp-devel

build:
  script:
    - cmake .
    - cmake --build .
